[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "trackastra-galaxy"
version = "1.0.1"
description = "Standalone Python CLI wrapper around Trackastra for segmentation and tracking on OME-Zarr data"
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }
authors = [
  { name = "Vladimír", email = "ulman@fi.muni.cz" },
  { name = "Khaled", email = "k.jumah@bradford.ac.uk" }
]
dependencies = [
  "ome-zarr>=0.14.0",
  "scikit-image",
  "trackastra>0.5"
]

classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "License :: OSI Approved :: MIT License",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: Bio-Informatics",
  "Topic :: Scientific/Engineering :: Image Processing"
]

[project.urls]
Homepage = "https://github.com/bioinfbrad/trackastra-galaxy"
Source = "https://github.com/bioinfbrad/trackastra-galaxy"
Issues = "https://github.com/bioinfbrad/trackastra-galaxy/issues"

[project.scripts]
trackastra-galaxy = "trackastra_galaxy.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
trackastra-galaxy = { path = ".", editable = true }

[tool.pixi.tasks]
